[project]
name = "cleanair-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools>=6.0.0",
    "colorama>=0.4.6",
    "django>=5.2.3",
    "dnspython>=2.7.0",
]
